import type {
  KgBusinessModelProfile,
  KgIndustryProfile,
  KgPatternCategory,
  KgPatternProfile,
  KgPlaybookStep,
  KgRuleActions,
  KgRuleConditions,
} from "@/db/schema";
import type { BusinessModelSlug, IndustrySlug } from "@/lib/knowledge-graph/taxonomy";

function profile(p: KgIndustryProfile): KgIndustryProfile {
  return p;
}

function patternProfile(p: KgPatternProfile): KgPatternProfile {
  return p;
}

function impl(
  items: { title: string; action: string }[],
): KgPatternProfile["implementationSteps"] {
  return items.map((item, i) => ({ ...item, order: i + 1 }));
}

export const SEED_INDUSTRIES: {
  slug: IndustrySlug;
  name: string;
  sortOrder: number;
  profile: KgIndustryProfile;
}[] = [
  {
    slug: "saas",
    name: "SaaS",
    sortOrder: 1,
    profile: profile({
      description:
        "Software-as-a-service companies grow through trial/demo conversion, activation, and expansion revenue.",
      characteristics: [
        "product-led or sales-assisted acquisition",
        "recurring revenue",
        "onboarding-critical activation",
      ],
      revenueModels: ["subscription", "freemium", "usage-based"],
      trustSignals: ["customer logos", "case studies", "security badges", "reviews"],
      marketingChannels: ["content SEO", "product-led growth", "paid search", "partners"],
      websiteFeatures: ["pricing page", "free trial", "demo CTA", "docs", "changelog"],
      contentStrategy: ["blog", "comparison pages", "use cases", "webinars"],
      integrations: ["CRM", "analytics", "SSO", "webhooks"],
      growthPriorities: ["trial conversion", "activation", "expansion revenue", "retention"],
      commonGaps: ["no free trial CTA", "weak pricing clarity", "missing case studies", "no product tour"],
      conversionPatterns: ["trial signup", "demo request", "pricing → checkout"],
      seoExpectations: ["comparison pages", "use-case landing pages", "docs indexed"],
      benchmarks: {
        expectedFeatures: [
          "pricing page",
          "free trial",
          "demo CTA",
          "case studies",
          "security badges",
          "docs",
        ],
        peerCategoryTargets: {
          conversion: 70,
          trust: 65,
          revenue: 70,
          seo: 60,
        },
        notes: "Peers with clear trial + proof convert high-intent traffic faster.",
      },
    }),
  },
  {
    slug: "ecommerce",
    name: "Ecommerce",
    sortOrder: 2,
    profile: profile({
      description:
        "Online retail grows through conversion rate, AOV, email capture, and repeat purchase.",
      characteristics: ["catalog-driven", "checkout-critical", "seasonal campaigns"],
      revenueModels: ["product sales", "subscriptions", "upsells"],
      trustSignals: ["reviews", "guarantees", "secure checkout", "return policy"],
      marketingChannels: ["email", "paid social", "SEO", "influencers"],
      websiteFeatures: ["product pages", "cart", "checkout", "collections"],
      contentStrategy: ["guides", "UGC", "lookbooks"],
      integrations: ["email ESP", "payments", "shipping"],
      growthPriorities: ["conversion rate", "AOV", "repeat purchase", "email capture"],
      commonGaps: ["weak reviews on PDP", "no email capture", "checkout friction", "missing upsells"],
      conversionPatterns: ["PDP → cart → checkout", "popup email capture", "bundles"],
      seoExpectations: ["product schema", "collection pages", "guides"],
      benchmarks: {
        expectedFeatures: [
          "product pages",
          "cart",
          "checkout",
          "reviews",
          "return policy",
          "email capture",
        ],
        peerCategoryTargets: {
          conversion: 75,
          trust: 70,
          marketing: 65,
          revenue: 70,
        },
      },
    }),
  },
  {
    slug: "healthcare",
    name: "Healthcare",
    sortOrder: 3,
    profile: profile({
      revenueModels: ["appointments", "insurance", "membership care"],
      trustSignals: ["credentials", "HIPAA notes", "testimonials", "provider bios"],
      marketingChannels: ["local SEO", "referrals", "education content"],
      websiteFeatures: ["booking", "services", "insurance info", "patient portal link"],
      contentStrategy: ["condition guides", "FAQs", "provider content"],
      integrations: ["scheduling", "CRM", "telehealth"],
      growthPriorities: ["booking conversion", "trust", "local visibility"],
    }),
  },
  {
    slug: "legal",
    name: "Legal",
    sortOrder: 4,
    profile: profile({
      revenueModels: ["hourly", "contingency", "retainers"],
      trustSignals: ["bar admissions", "case results", "awards", "testimonials"],
      marketingChannels: ["referrals", "local SEO", "thought leadership"],
      websiteFeatures: ["practice areas", "attorney bios", "consultation CTA"],
      contentStrategy: ["guides", "FAQs", "case insights"],
      integrations: ["intake forms", "CRM", "scheduling"],
      growthPriorities: ["lead intake", "authority", "consultation booking"],
    }),
  },
  {
    slug: "restaurants",
    name: "Restaurants",
    sortOrder: 5,
    profile: profile({
      revenueModels: ["dine-in", "delivery", "catering", "events"],
      trustSignals: ["reviews", "photos", "awards", "hygiene ratings"],
      marketingChannels: ["local SEO", "social", "email", "delivery apps"],
      websiteFeatures: ["menu", "reservations", "location", "ordering"],
      contentStrategy: ["menu stories", "events", "social proof"],
      integrations: ["reservations", "ordering", "POS"],
      growthPriorities: ["reservations", "reviews", "repeat visits", "catering"],
    }),
  },
  {
    slug: "real_estate",
    name: "Real Estate",
    sortOrder: 6,
    profile: profile({
      revenueModels: ["commissions", "property management", "referrals"],
      trustSignals: ["agent bios", "sold listings", "testimonials", "licenses"],
      marketingChannels: ["listings SEO", "social", "email nurture"],
      websiteFeatures: ["listings search", "valuation CTA", "neighborhood guides"],
      contentStrategy: ["market reports", "buyer/seller guides"],
      integrations: ["MLS", "CRM", "scheduling"],
      growthPriorities: ["lead capture", "nurture", "authority"],
    }),
  },
  {
    slug: "churches",
    name: "Churches",
    sortOrder: 7,
    profile: profile({
      description:
        "Church organizations grow first-time visits, community engagement, and generous giving.",
      characteristics: ["community-first", "event-driven", "local + online"],
      revenueModels: ["giving", "events", "membership"],
      trustSignals: ["leadership", "beliefs", "community stories"],
      marketingChannels: ["local SEO", "social", "email", "events"],
      websiteFeatures: ["service times", "giving", "sermons", "events", "visit CTA"],
      contentStrategy: ["sermons", "devotionals", "community stories"],
      integrations: ["giving platform", "email", "livestream"],
      growthPriorities: ["first visit", "giving", "community engagement"],
      commonGaps: ["buried give CTA", "no visit path", "sermons not indexed", "weak events calendar"],
      conversionPatterns: ["plan a visit", "give online", "event registration"],
      seoExpectations: ["service times", "location pages", "sermon archive"],
      benchmarks: {
        expectedFeatures: ["service times", "giving", "sermons", "events", "visit CTA"],
        peerCategoryTargets: { revenue: 60, content: 65, conversion: 55, marketing: 60 },
      },
    }),
  },
  {
    slug: "nonprofits",
    name: "Nonprofits",
    sortOrder: 8,
    profile: profile({
      description:
        "Nonprofits convert mission into donations, recurring giving, and volunteer pipelines.",
      characteristics: ["mission-led", "donor trust critical", "campaign cycles"],
      revenueModels: ["donations", "grants", "membership"],
      trustSignals: ["impact metrics", "transparency", "board", "stories"],
      marketingChannels: ["email", "social", "partners", "SEO"],
      websiteFeatures: ["donate", "impact", "volunteer", "newsletter"],
      contentStrategy: ["impact stories", "reports", "campaigns"],
      integrations: ["donation processor", "CRM", "email"],
      growthPriorities: ["donations", "recurring giving", "volunteer pipeline"],
      commonGaps: ["unclear donate path", "no impact metrics", "no recurring giving", "weak email capture"],
      conversionPatterns: ["donate now", "monthly giving", "volunteer signup"],
      seoExpectations: ["cause pages", "impact reports", "campaign landing pages"],
      benchmarks: {
        expectedFeatures: ["donate", "impact", "volunteer", "newsletter", "recurring giving"],
        peerCategoryTargets: { revenue: 65, trust: 75, marketing: 60, conversion: 60 },
      },
    }),
  },
  {
    slug: "education",
    name: "Education",
    sortOrder: 9,
    profile: profile({
      revenueModels: ["tuition", "courses", "memberships"],
      trustSignals: ["accreditation", "outcomes", "faculty", "reviews"],
      marketingChannels: ["SEO", "email", "webinars", "partners"],
      websiteFeatures: ["programs", "admissions CTA", "tuition", "resources"],
      contentStrategy: ["guides", "student stories", "curriculum"],
      integrations: ["LMS", "CRM", "payments"],
      growthPriorities: ["enrollment", "nurture", "retention"],
    }),
  },
  {
    slug: "financial_services",
    name: "Financial Services",
    sortOrder: 10,
    profile: profile({
      revenueModels: ["AUM fees", "commissions", "subscriptions"],
      trustSignals: ["credentials", "disclosures", "client reviews", "security"],
      marketingChannels: ["referrals", "content", "events", "SEO"],
      websiteFeatures: ["services", "team", "consultation CTA", "calculators"],
      contentStrategy: ["market insights", "guides", "FAQs"],
      integrations: ["CRM", "scheduling", "secure forms"],
      growthPriorities: ["trust", "consultations", "referrals"],
    }),
  },
  {
    slug: "professional_services",
    name: "Professional Services",
    sortOrder: 11,
    profile: profile({
      description:
        "Agencies and firms win with proof, consultation paths, and retainer expansion.",
      characteristics: ["relationship-led", "portfolio proof", "high-ticket sales"],
      revenueModels: ["project", "retainer", "hourly"],
      trustSignals: ["case studies", "logos", "team bios", "reviews"],
      marketingChannels: ["referrals", "content", "LinkedIn", "SEO"],
      websiteFeatures: ["services", "case studies", "contact CTA"],
      contentStrategy: ["thought leadership", "guides", "webinars"],
      integrations: ["CRM", "scheduling", "proposals"],
      growthPriorities: ["lead quality", "authority", "retainers"],
      commonGaps: ["no case studies", "weak consultation CTA", "no nurture automation"],
      conversionPatterns: ["book a consultation", "proposal request", "contact form"],
      seoExpectations: ["service pages", "thought leadership", "case study SEO"],
      benchmarks: {
        expectedFeatures: ["services", "case studies", "contact CTA", "team bios", "reviews"],
        peerCategoryTargets: { trust: 75, authority: 70, conversion: 65, marketing: 60 },
      },
    }),
  },
  {
    slug: "local_services",
    name: "Local Services",
    sortOrder: 12,
    profile: profile({
      description:
        "Local businesses grow through quote conversion, reviews, and service-area visibility.",
      characteristics: ["geo-focused", "phone/quote critical", "review-sensitive"],
      revenueModels: ["service jobs", "memberships", "maintenance plans"],
      trustSignals: ["reviews", "licenses", "guarantees", "photos"],
      marketingChannels: ["local SEO", "Google Business", "referrals"],
      websiteFeatures: ["services", "service area", "quote CTA", "phone"],
      contentStrategy: ["service pages", "FAQs", "tips"],
      integrations: ["scheduling", "CRM", "payments"],
      growthPriorities: ["quote conversion", "reviews", "repeat jobs"],
      commonGaps: ["no quote CTA", "missing service area pages", "few reviews", "no booking"],
      conversionPatterns: ["get a quote", "call now", "book online"],
      seoExpectations: ["GBP alignment", "service + city pages", "FAQ schema"],
      benchmarks: {
        expectedFeatures: ["services", "service area", "quote CTA", "phone", "reviews"],
        peerCategoryTargets: { seo: 70, conversion: 70, trust: 75, marketing: 55 },
      },
    }),
  },
  {
    slug: "creator_economy",
    name: "Creator Economy",
    sortOrder: 13,
    profile: profile({
      description:
        "Creators monetize audience through memberships, digital products, sponsorships, and community.",
      characteristics: ["audience-owned", "content-led", "multi-platform"],
      revenueModels: ["membership", "digital products", "sponsorships", "affiliates"],
      trustSignals: ["testimonials", "social proof", "creator bio", "sample content"],
      marketingChannels: ["email", "YouTube", "social", "podcast", "SEO"],
      websiteFeatures: ["newsletter signup", "membership CTA", "digital products", "about"],
      contentStrategy: ["newsletter", "courses", "podcast", "free lead magnets"],
      integrations: ["email ESP", "payments", "membership platform", "analytics"],
      growthPriorities: ["list growth", "offer conversion", "retention", "upsells"],
      commonGaps: ["no owned email list", "weak offer page", "no membership path", "scattered CTAs"],
      conversionPatterns: ["subscribe", "join membership", "buy digital product"],
      seoExpectations: ["pillar content", "show notes", "offer landing pages"],
      benchmarks: {
        expectedFeatures: [
          "newsletter signup",
          "membership CTA",
          "digital products",
          "about",
          "testimonials",
        ],
        peerCategoryTargets: {
          marketing: 75,
          revenue: 70,
          content: 75,
          conversion: 65,
        },
        notes: "Peers with a clear owned-audience path outperform link-in-bio only creators.",
      },
    }),
  },
];
export const SEED_MODELS: {
  slug: BusinessModelSlug;
  name: string;
  description: string;
  typicalIndustries: string[];
  sortOrder: number;
  profile: KgBusinessModelProfile;
}[] = [
  {
    slug: "subscription",
    name: "Subscription",
    description: "Recurring revenue via plans or seats.",
    typicalIndustries: ["saas", "ecommerce", "education"],
    sortOrder: 1,
    profile: {
      revenueStructure: ["monthly/annual plans", "seats", "usage add-ons"],
      customerJourney: ["visit", "trial/demo", "paid plan", "expand"],
      growthLevers: ["trial conversion", "activation", "expansion revenue", "reduce churn"],
      commonGaps: ["no free trial", "weak pricing page", "no expansion path", "poor onboarding"],
      trustRequirements: ["logos", "case studies", "security", "reviews"],
      conversionPatterns: ["trial signup", "demo request", "self-serve checkout"],
      retentionStrategies: ["onboarding", "success milestones", "annual plans"],
      revenueStages: [
        { id: "visitor", label: "Visitor", description: "Awareness traffic" },
        { id: "lead", label: "Lead", description: "Captured interest" },
        { id: "trial", label: "Trial", description: "Product experience" },
        { id: "customer", label: "Customer", description: "Paid conversion" },
        { id: "retention", label: "Retention", description: "Ongoing value" },
        { id: "expansion", label: "Expansion", description: "Upsell / seats" },
      ],
      benchmarks: {
        expectedCapabilities: ["pricing page", "free trial", "demo CTA", "billing portal", "onboarding"],
        notes: "Peers with clear trial → paid paths convert high-intent traffic faster.",
      },
    },
  },
  {
    slug: "product_commerce",
    name: "Ecommerce",
    description: "Direct product sales via catalog and checkout.",
    typicalIndustries: ["ecommerce", "creator_economy"],
    sortOrder: 2,
    profile: {
      revenueStructure: ["product sales", "bundles", "subscriptions add-on"],
      customerJourney: ["browse", "PDP", "cart", "checkout", "repeat"],
      growthLevers: ["conversion rate", "AOV", "email capture", "repeat purchase"],
      commonGaps: ["checkout friction", "weak reviews", "no email capture", "no upsells"],
      trustRequirements: ["reviews", "return policy", "secure checkout"],
      conversionPatterns: ["add to cart", "express checkout", "bundles"],
      retentionStrategies: ["email flows", "loyalty", "replenishment"],
      revenueStages: [
        { id: "visitor", label: "Visitor" },
        { id: "browse", label: "Browse / PDP" },
        { id: "cart", label: "Cart" },
        { id: "checkout", label: "Checkout" },
        { id: "customer", label: "Customer" },
        { id: "retention", label: "Repeat / Retention" },
      ],
      benchmarks: {
        expectedCapabilities: ["product pages", "cart", "checkout", "reviews", "email capture"],
      },
    },
  },
  {
    slug: "lead_generation",
    name: "Lead Generation",
    description: "Website converts visitors into sales-qualified leads.",
    typicalIndustries: ["professional_services", "local_services", "financial_services", "legal", "healthcare"],
    sortOrder: 3,
    profile: {
      revenueStructure: ["offline close", "project / retainer after lead"],
      customerJourney: ["visit", "lead capture", "nurture", "sales close"],
      growthLevers: ["form conversion", "speed-to-lead", "nurture", "authority"],
      commonGaps: ["weak CTA", "no booking", "no nurture", "unclear offer"],
      trustRequirements: ["case studies", "reviews", "credentials"],
      conversionPatterns: ["quote form", "book a call", "consultation"],
      retentionStrategies: ["CRM nurture", "content drip", "referral ask"],
      revenueStages: [
        { id: "visitor", label: "Visitor" },
        { id: "lead", label: "Lead" },
        { id: "nurture", label: "Nurture" },
        { id: "opportunity", label: "Sales opportunity" },
        { id: "customer", label: "Customer" },
        { id: "retention", label: "Retention / Referral" },
      ],
      benchmarks: {
        expectedCapabilities: ["clear CTA", "lead form", "booking", "case studies", "CRM/email"],
      },
    },
  },
  {
    slug: "marketplace",
    name: "Marketplace",
    description: "Two-sided platform connecting buyers and sellers.",
    typicalIndustries: ["ecommerce", "professional_services"],
    sortOrder: 4,
    profile: {
      revenueStructure: ["take rate", "listing fees", "subscriptions for sellers"],
      customerJourney: ["discover", "match", "transact", "review", "repeat"],
      growthLevers: ["liquidity", "trust", "search/match quality", "seller tools"],
      commonGaps: ["thin supply", "weak trust layer", "poor matching", "no reviews"],
      trustRequirements: ["reviews", "verification", "dispute handling"],
      conversionPatterns: ["listing → inquire → book/buy"],
      retentionStrategies: ["seller incentives", "buyer loyalty", "notifications"],
      revenueStages: [
        { id: "visitor", label: "Visitor" },
        { id: "side_a", label: "Buyer acquisition" },
        { id: "side_b", label: "Seller acquisition" },
        { id: "match", label: "Match / Transaction" },
        { id: "retention", label: "Repeat liquidity" },
      ],
      benchmarks: {
        expectedCapabilities: ["listings", "search", "profiles", "reviews", "payments"],
      },
    },
  },
  {
    slug: "advertising",
    name: "Advertising",
    description: "Monetize audience via ads, sponsorships, or media kits.",
    typicalIndustries: ["creator_economy", "education"],
    sortOrder: 5,
    profile: {
      revenueStructure: ["sponsorships", "display ads", "affiliate", "media kit deals"],
      customerJourney: ["audience growth", "engagement", "sponsor pitch", "campaign"],
      growthLevers: ["audience size", "engagement", "rate card clarity", "packaging"],
      commonGaps: ["no media kit", "unclear rates", "weak audience proof", "no sponsor CTA"],
      trustRequirements: ["audience metrics", "case studies", "brand safety"],
      conversionPatterns: ["advertise with us", "sponsor inquiry"],
      retentionStrategies: ["campaign reporting", "package renewals"],
      revenueStages: [
        { id: "visitor", label: "Audience visitor" },
        { id: "engage", label: "Engagement" },
        { id: "sponsor_lead", label: "Sponsor lead" },
        { id: "campaign", label: "Campaign / Ad" },
        { id: "renewal", label: "Renewal" },
      ],
      benchmarks: {
        expectedCapabilities: ["media kit", "advertise CTA", "audience stats", "case studies"],
      },
    },
  },
  {
    slug: "transaction_based",
    name: "Transaction Based",
    description: "Revenue from fees on completed transactions or bookings.",
    typicalIndustries: ["saas", "local_services", "real_estate", "ecommerce"],
    sortOrder: 6,
    profile: {
      revenueStructure: ["per-transaction fees", "booking fees", "payment take rate"],
      customerJourney: ["discover", "configure", "transact", "fulfill"],
      growthLevers: ["transaction volume", "fee clarity", "checkout completion"],
      commonGaps: ["unclear fees", "checkout drop-off", "weak payment trust"],
      trustRequirements: ["secure payments", "transparent fees", "reviews"],
      conversionPatterns: ["book/pay now", "checkout"],
      retentionStrategies: ["receipts", "reorder", "saved payments"],
      revenueStages: [
        { id: "visitor", label: "Visitor" },
        { id: "intent", label: "Intent / Configure" },
        { id: "transaction", label: "Transaction" },
        { id: "fulfillment", label: "Fulfillment" },
        { id: "repeat", label: "Repeat transaction" },
      ],
      benchmarks: {
        expectedCapabilities: ["clear pricing", "checkout", "payment", "confirmation", "receipts"],
      },
    },
  },
  {
    slug: "agency",
    name: "Agency",
    description: "Client services delivered by a team on retainers or projects.",
    typicalIndustries: ["professional_services"],
    sortOrder: 7,
    profile: {
      revenueStructure: ["project", "retainer", "hourly"],
      customerJourney: ["proof", "consult", "proposal", "delivery", "retain"],
      growthLevers: ["authority", "lead quality", "retainers", "referrals"],
      commonGaps: ["no case studies", "weak consultation CTA", "no nurture"],
      trustRequirements: ["case studies", "logos", "team bios"],
      conversionPatterns: ["book consultation", "contact"],
      retentionStrategies: ["QBRs", "upsell packages", "referrals"],
      revenueStages: [
        { id: "visitor", label: "Visitor" },
        { id: "lead", label: "Lead" },
        { id: "consult", label: "Consultation" },
        { id: "customer", label: "Client" },
        { id: "retention", label: "Retainer / Expansion" },
      ],
      benchmarks: {
        expectedCapabilities: ["services", "case studies", "contact CTA", "proof"],
      },
    },
  },
  {
    slug: "consulting",
    name: "Consulting",
    description: "Expert advisory sold as engagements.",
    typicalIndustries: ["professional_services", "financial_services", "legal"],
    sortOrder: 8,
    profile: {
      revenueStructure: ["engagement fees", "retainers"],
      customerJourney: ["authority", "inquiry", "scope", "delivery"],
      growthLevers: ["thought leadership", "referrals", "premium packaging"],
      commonGaps: ["unclear offer", "no booking", "thin proof"],
      trustRequirements: ["credentials", "outcomes", "testimonials"],
      conversionPatterns: ["book a call", "application form"],
      retentionStrategies: ["ongoing advisory", "productized follow-ons"],
      revenueStages: [
        { id: "visitor", label: "Visitor" },
        { id: "lead", label: "Lead" },
        { id: "scope", label: "Scope / Proposal" },
        { id: "customer", label: "Engagement" },
        { id: "retention", label: "Ongoing advisory" },
      ],
      benchmarks: {
        expectedCapabilities: ["offer clarity", "booking", "proof", "credentials"],
      },
    },
  },
  {
    slug: "membership",
    name: "Membership",
    description: "Ongoing access to community, content, or benefits.",
    typicalIndustries: ["education", "nonprofits", "churches", "creator_economy"],
    sortOrder: 9,
    profile: {
      revenueStructure: ["monthly membership", "tiers"],
      customerJourney: ["taste free", "join", "engage", "renew"],
      growthLevers: ["list growth", "activation", "community", "tier upgrades"],
      commonGaps: ["no join CTA", "weak member value", "no community"],
      trustRequirements: ["member stories", "preview content"],
      conversionPatterns: ["join now", "free trial membership"],
      retentionStrategies: ["community events", "exclusive content"],
      revenueStages: [
        { id: "visitor", label: "Visitor" },
        { id: "lead", label: "Subscriber / Lead" },
        { id: "member", label: "Member" },
        { id: "engage", label: "Engagement" },
        { id: "renew", label: "Renew / Upgrade" },
      ],
      benchmarks: {
        expectedCapabilities: ["membership CTA", "pricing tiers", "member login", "community"],
      },
    },
  },
  {
    slug: "digital_products",
    name: "Digital Products",
    description: "Courses, templates, downloads, and info products.",
    typicalIndustries: ["education", "professional_services", "saas", "creator_economy"],
    sortOrder: 10,
    profile: {
      revenueStructure: ["one-time purchases", "course bundles"],
      customerJourney: ["content", "offer page", "purchase", "fulfill"],
      growthLevers: ["offer clarity", "list", "upsells", "testimonials"],
      commonGaps: ["weak offer page", "no checkout", "no upsell"],
      trustRequirements: ["testimonials", "previews", "guarantees"],
      conversionPatterns: ["buy now", "enroll"],
      retentionStrategies: ["bonuses", "community", "advanced offers"],
      revenueStages: [
        { id: "visitor", label: "Visitor" },
        { id: "lead", label: "Lead / List" },
        { id: "offer", label: "Offer page" },
        { id: "purchase", label: "Purchase" },
        { id: "upsell", label: "Upsell / Next offer" },
      ],
      benchmarks: {
        expectedCapabilities: ["offer page", "checkout", "testimonials", "delivery"],
      },
    },
  },
  {
    slug: "local_business",
    name: "Local Business",
    description: "Location-based services or storefronts.",
    typicalIndustries: ["restaurants", "local_services", "healthcare", "real_estate"],
    sortOrder: 11,
    profile: {
      revenueStructure: ["jobs", "appointments", "walk-ins"],
      customerJourney: ["local search", "trust", "book/call", "service"],
      growthLevers: ["local SEO", "reviews", "booking conversion"],
      commonGaps: ["no booking", "few reviews", "weak NAP"],
      trustRequirements: ["reviews", "photos", "licenses"],
      conversionPatterns: ["call now", "book online", "get quote"],
      retentionStrategies: ["reminders", "memberships", "referrals"],
      revenueStages: [
        { id: "visitor", label: "Local visitor" },
        { id: "trust", label: "Trust check" },
        { id: "book", label: "Book / Call" },
        { id: "customer", label: "Served customer" },
        { id: "retention", label: "Repeat / Referral" },
      ],
      benchmarks: {
        expectedCapabilities: ["phone", "booking", "reviews", "service area"],
      },
    },
  },
  {
    slug: "franchise",
    name: "Franchise",
    description: "Branded multi-location model.",
    typicalIndustries: ["restaurants", "local_services"],
    sortOrder: 12,
    profile: {
      revenueStructure: ["franchise fees", "royalties", "location sales"],
      customerJourney: ["brand discovery", "location", "purchase", "loyalty"],
      growthLevers: ["brand consistency", "local pages", "franchisee acquisition"],
      commonGaps: ["weak location finder", "inconsistent CTAs"],
      trustRequirements: ["brand proof", "reviews"],
      conversionPatterns: ["find a location", "order", "franchise inquiry"],
      retentionStrategies: ["loyalty apps", "local events"],
      revenueStages: [
        { id: "visitor", label: "Visitor" },
        { id: "location", label: "Location select" },
        { id: "purchase", label: "Purchase" },
        { id: "loyalty", label: "Loyalty" },
      ],
      benchmarks: {
        expectedCapabilities: ["locations", "brand story", "order/CTA", "franchise info"],
      },
    },
  },
  {
    slug: "nonprofit",
    name: "Donation / Nonprofit",
    description: "Mission-driven donations and programs.",
    typicalIndustries: ["nonprofits", "churches", "education"],
    sortOrder: 13,
    profile: {
      revenueStructure: ["one-time gifts", "recurring giving", "grants"],
      customerJourney: ["mission", "trust", "give", "steward"],
      growthLevers: ["donate CTA", "impact proof", "recurring gifts"],
      commonGaps: ["buried give CTA", "no impact metrics", "no recurring option"],
      trustRequirements: ["transparency", "impact stories", "board"],
      conversionPatterns: ["donate now", "monthly giving"],
      retentionStrategies: ["donor updates", "campaigns"],
      revenueStages: [
        { id: "visitor", label: "Visitor" },
        { id: "trust", label: "Trust / Impact" },
        { id: "donate", label: "Donate" },
        { id: "recurring", label: "Recurring donor" },
        { id: "advocate", label: "Advocate / Volunteer" },
      ],
      benchmarks: {
        expectedCapabilities: ["donate", "impact", "recurring giving", "newsletter"],
      },
    },
  },
  {
    slug: "hybrid",
    name: "Hybrid",
    description: "Multiple revenue models combined.",
    typicalIndustries: [],
    sortOrder: 14,
    profile: {
      revenueStructure: ["mixed streams"],
      customerJourney: ["multi-path"],
      growthLevers: ["clarify primary path", "unify CTAs"],
      commonGaps: ["competing CTAs", "unclear primary revenue path"],
      trustRequirements: ["consistent proof across offers"],
      conversionPatterns: ["primary offer first"],
      retentionStrategies: ["cross-sell between streams"],
      revenueStages: [
        { id: "visitor", label: "Visitor" },
        { id: "path", label: "Choose path" },
        { id: "convert", label: "Convert" },
        { id: "expand", label: "Cross-sell / Expand" },
      ],
      benchmarks: {
        expectedCapabilities: ["primary CTA", "secondary offers", "clear packaging"],
        notes: "Hybrids win when one path is obviously primary.",
      },
    },
  },
];

export const SEED_PATTERNS: {
  slug: string;
  name: string;
  purpose: string;
  category: KgPatternCategory;
  description: string;
  profile: KgPatternProfile;
  outcomes: string[];
  dependencies: string[];
  difficulty: string;
  roiEstimate: number;
  relatedEntitySlugs: string[];
}[] = [
  {
    slug: "lead_generation",
    name: "Lead Generation Pattern",
    purpose: "Capture and qualify demand from the site.",
    category: "acquisition",
    description: "Forms, magnets, and CTAs that turn visitors into leads.",
    profile: patternProfile({
      applicableIndustries: [],
      applicableBusinessModels: ["lead_generation", "agency", "consulting", "subscription"],
      requiredConditions: ["form", "cta", "lead", "contact", "demo"],
      maturityLevels: ["early", "growth"],
      goalTypes: ["leads", "conversions"],
      implementationSteps: impl([
        { title: "Add primary CTA", action: "Place one clear lead CTA above the fold." },
        { title: "Offer a magnet", action: "Ship a checklist or guide for email capture." },
        { title: "Route to CRM", action: "Sync submissions to follow-up workflows." },
      ]),
      impactScore: 88,
      revenuePotential: 5,
      expectedOutcomes: ["more leads", "lower CAC"],
    }),
    outcomes: ["more leads", "lower CAC"],
    dependencies: [],
    difficulty: "medium",
    roiEstimate: 5,
    relatedEntitySlugs: ["forms", "lead_magnet"],
  },
  {
    slug: "membership",
    name: "Membership Pattern",
    purpose: "Create recurring access and community value.",
    category: "revenue",
    description: "Paid membership access with recurring billing and member value.",
    profile: patternProfile({
      applicableIndustries: ["creator_economy", "education", "nonprofits"],
      applicableBusinessModels: ["membership", "subscription", "digital_products"],
      requiredConditions: ["member", "membership", "subscribe", "join"],
      maturityLevels: ["growth", "scale"],
      goalTypes: ["revenue", "subscribers"],
      implementationSteps: impl([
        { title: "Define tiers", action: "Publish clear membership levels and benefits." },
        { title: "Gate value", action: "Ship member-only content or community." },
        { title: "Automate billing", action: "Wire recurring payments and renewals." },
      ]),
      impactScore: 82,
      revenuePotential: 4,
    }),
    outcomes: ["MRR", "retention"],
    dependencies: ["lead_generation"],
    difficulty: "hard",
    roiEstimate: 4,
    relatedEntitySlugs: ["membership"],
  },
  {
    slug: "authority",
    name: "Authority Pattern",
    purpose: "Build proof and inbound trust.",
    category: "authority",
    description: "Case studies, backlinks, and expert content that raise close rates.",
    profile: patternProfile({
      applicableIndustries: [],
      applicableBusinessModels: [],
      requiredConditions: ["case study", "press", "expert", "backlink"],
      maturityLevels: ["early", "growth", "scale"],
      goalTypes: ["authority", "seo"],
      implementationSteps: impl([
        { title: "Publish proof", action: "Ship 2–3 outcome case studies." },
        { title: "Earn mentions", action: "Pursue guest posts and partner links." },
        { title: "Surface credentials", action: "Feature logos and expertise on key pages." },
      ]),
      impactScore: 78,
      revenuePotential: 4,
    }),
    outcomes: ["referrals", "higher close rate"],
    dependencies: [],
    difficulty: "medium",
    roiEstimate: 4,
    relatedEntitySlugs: ["backlinks", "case_studies"],
  },
  {
    slug: "referral",
    name: "Referral Pattern",
    purpose: "Turn customers into acquisition channel.",
    category: "acquisition",
    description: "Incentives and loops that convert customers into advocates.",
    profile: patternProfile({
      applicableIndustries: ["saas", "ecommerce", "creator_economy"],
      applicableBusinessModels: ["subscription", "product_commerce", "membership"],
      requiredConditions: ["referral", "invite", "share"],
      maturityLevels: ["growth", "scale"],
      goalTypes: ["leads", "revenue"],
      implementationSteps: impl([
        { title: "Define reward", action: "Offer clear two-sided referral incentives." },
        { title: "Add share path", action: "Put referral CTAs in post-purchase flows." },
        { title: "Track attribution", action: "Instrument referral codes and attribution." },
      ]),
      impactScore: 80,
      revenuePotential: 5,
    }),
    outcomes: ["lower CAC", "viral loops"],
    dependencies: ["retention"],
    difficulty: "medium",
    roiEstimate: 5,
    relatedEntitySlugs: ["referral_program"],
  },
  {
    slug: "newsletter",
    name: "Newsletter Pattern",
    purpose: "Own an audience via email.",
    category: "acquisition",
    description: "Owned list growth and nurture via email capture.",
    profile: patternProfile({
      applicableIndustries: [],
      applicableBusinessModels: [],
      requiredConditions: ["newsletter", "subscribe", "email"],
      maturityLevels: ["early", "growth"],
      goalTypes: ["subscribers", "leads"],
      implementationSteps: impl([
        { title: "Add capture", action: "Place signup above the fold on high-traffic pages." },
        { title: "Welcome sequence", action: "Send a 3–5 email onboarding drip." },
        { title: "Segment", action: "Tag subscribers by interest for later offers." },
      ]),
      impactScore: 85,
      revenuePotential: 5,
    }),
    outcomes: ["owned traffic", "nurture"],
    dependencies: ["lead_generation"],
    difficulty: "easy",
    roiEstimate: 5,
    relatedEntitySlugs: ["newsletter", "email"],
  },
  {
    slug: "community",
    name: "Community Pattern",
    purpose: "Engage peers for retention and advocacy.",
    category: "retention",
    description: "Peer spaces that increase retention and content flywheels.",
    profile: patternProfile({
      applicableIndustries: ["creator_economy", "education", "churches", "nonprofits"],
      applicableBusinessModels: ["membership", "nonprofit", "subscription"],
      requiredConditions: ["community", "forum", "discord", "members"],
      maturityLevels: ["growth", "scale"],
      goalTypes: ["subscribers", "product"],
      implementationSteps: impl([
        { title: "Pick a hub", action: "Choose one community channel and own it." },
        { title: "Seed rituals", action: "Run recurring events or threads." },
        { title: "Highlight members", action: "Feature member wins publicly." },
      ]),
      impactScore: 70,
      revenuePotential: 3,
    }),
    outcomes: ["retention", "content"],
    dependencies: ["membership"],
    difficulty: "hard",
    roiEstimate: 3,
    relatedEntitySlugs: ["community"],
  },
  {
    slug: "upsell",
    name: "Upsell Pattern",
    purpose: "Expand revenue from existing customers.",
    category: "revenue",
    description: "Bundles, packs, and expansion offers that raise AOV / NRR.",
    profile: patternProfile({
      applicableIndustries: ["saas", "ecommerce", "creator_economy"],
      applicableBusinessModels: ["subscription", "product_commerce", "digital_products"],
      requiredConditions: ["pricing", "upgrade", "bundle", "pack"],
      maturityLevels: ["growth", "scale"],
      goalTypes: ["revenue"],
      implementationSteps: impl([
        { title: "Map expansion", action: "Identify next-best offer after purchase." },
        { title: "Surface packs", action: "Add bundles on PDPs or account pages." },
        { title: "Trigger nudges", action: "Automate upgrade prompts at usage milestones." },
      ]),
      impactScore: 86,
      revenuePotential: 5,
    }),
    outcomes: ["AOV", "expansion"],
    dependencies: [],
    difficulty: "medium",
    roiEstimate: 5,
    relatedEntitySlugs: ["pricing", "packs"],
  },
  {
    slug: "retention",
    name: "Retention Pattern",
    purpose: "Reduce churn and increase LTV.",
    category: "retention",
    description: "Onboarding and lifecycle loops that protect LTV.",
    profile: patternProfile({
      applicableIndustries: [],
      applicableBusinessModels: ["subscription", "membership", "product_commerce"],
      requiredConditions: ["onboard", "churn", "win-back", "lifecycle"],
      maturityLevels: ["growth", "scale"],
      goalTypes: ["revenue", "product"],
      implementationSteps: impl([
        { title: "Define activation", action: "Pick one activation metric and instrument it." },
        { title: "Onboard fast", action: "Ship a guided first-week experience." },
        { title: "Win-back", action: "Automate re-engagement for dormant users." },
      ]),
      impactScore: 84,
      revenuePotential: 4,
    }),
    outcomes: ["LTV", "NRR"],
    dependencies: [],
    difficulty: "medium",
    roiEstimate: 4,
    relatedEntitySlugs: ["onboarding", "automation"],
  },
  {
    slug: "seo_pillar",
    name: "SEO Pillar Pattern",
    purpose: "Own high-intent search with pillar + cluster content.",
    category: "seo",
    description: "Pillar pages and supporting clusters that compound organic traffic.",
    profile: patternProfile({
      applicableIndustries: [],
      applicableBusinessModels: [],
      requiredConditions: ["blog", "guide", "seo", "pillar"],
      maturityLevels: ["early", "growth", "scale"],
      goalTypes: ["seo", "leads"],
      implementationSteps: impl([
        { title: "Pick pillars", action: "Choose 2–3 commercial topics." },
        { title: "Ship clusters", action: "Publish supporting articles that link up." },
        { title: "Internal links", action: "Connect clusters to conversion pages." },
      ]),
      impactScore: 76,
      revenuePotential: 4,
    }),
    outcomes: ["organic traffic", "inbound leads"],
    dependencies: [],
    difficulty: "medium",
    roiEstimate: 4,
    relatedEntitySlugs: ["blog", "programmatic_seo"],
  },
  {
    slug: "local_seo",
    name: "Local SEO Pattern",
    purpose: "Win map pack and local intent.",
    category: "seo",
    description: "GBP, local pages, and reviews for local discovery.",
    profile: patternProfile({
      applicableIndustries: ["restaurants", "local_services", "healthcare", "legal", "real_estate"],
      applicableBusinessModels: ["local_business", "franchise", "lead_generation"],
      requiredConditions: ["local", "google", "maps", "near me", "hours"],
      maturityLevels: ["early", "growth"],
      goalTypes: ["seo", "leads"],
      implementationSteps: impl([
        { title: "Claim GBP", action: "Complete and verify Google Business Profile." },
        { title: "Local pages", action: "Publish service-area landing pages." },
        { title: "Review loop", action: "Ask happy customers for reviews weekly." },
      ]),
      impactScore: 83,
      revenuePotential: 5,
    }),
    outcomes: ["local visibility", "qualified calls"],
    dependencies: [],
    difficulty: "easy",
    roiEstimate: 5,
    relatedEntitySlugs: ["local_seo", "reviews"],
  },
  {
    slug: "social_proof",
    name: "Social Proof Pattern",
    purpose: "Reduce purchase anxiety with credible proof.",
    category: "trust",
    description: "Reviews, logos, and testimonials on conversion paths.",
    profile: patternProfile({
      applicableIndustries: [],
      applicableBusinessModels: [],
      requiredConditions: ["review", "testimonial", "logo", "rating"],
      maturityLevels: ["early", "growth"],
      goalTypes: ["conversions", "authority"],
      implementationSteps: impl([
        { title: "Collect proof", action: "Gather reviews and logos from happy customers." },
        { title: "Place on path", action: "Put proof next to primary CTAs." },
        { title: "Refresh often", action: "Rotate recent wins monthly." },
      ]),
      impactScore: 81,
      revenuePotential: 4,
    }),
    outcomes: ["higher conversion", "trust"],
    dependencies: [],
    difficulty: "easy",
    roiEstimate: 4,
    relatedEntitySlugs: ["reviews", "case_studies"],
  },
  {
    slug: "checkout_optimization",
    name: "Checkout Optimization Pattern",
    purpose: "Remove friction between intent and payment.",
    category: "conversion",
    description: "Shorter checkouts, trust cues, and clear CTAs at purchase.",
    profile: patternProfile({
      applicableIndustries: ["ecommerce"],
      applicableBusinessModels: ["product_commerce", "transaction_based"],
      requiredConditions: ["checkout", "cart", "buy", "payment"],
      maturityLevels: ["early", "growth", "scale"],
      goalTypes: ["conversions", "revenue"],
      implementationSteps: impl([
        { title: "Audit steps", action: "Count clicks from cart to paid." },
        { title: "Add trust cues", action: "Show guarantees and secure payment badges." },
        { title: "Recover carts", action: "Automate abandoned-cart reminders." },
      ]),
      impactScore: 90,
      revenuePotential: 5,
    }),
    outcomes: ["conversion rate", "AOV"],
    dependencies: [],
    difficulty: "medium",
    roiEstimate: 5,
    relatedEntitySlugs: ["checkout_friction", "pricing"],
  },
  {
    slug: "trial_demo",
    name: "Trial / Demo Pattern",
    purpose: "Lower commitment to start product evaluation.",
    category: "conversion",
    description: "Free trial or demo paths that convert evaluators.",
    profile: patternProfile({
      applicableIndustries: ["saas", "professional_services", "financial_services"],
      applicableBusinessModels: ["subscription", "lead_generation", "consulting"],
      requiredConditions: ["trial", "demo", "book", "schedule"],
      maturityLevels: ["early", "growth"],
      goalTypes: ["conversions", "leads", "product"],
      implementationSteps: impl([
        { title: "Pick path", action: "Choose trial or booked demo as primary CTA." },
        { title: "Reduce friction", action: "Ask for minimal fields to start." },
        { title: "Nurture", action: "Automate day-1 and day-3 activation emails." },
      ]),
      impactScore: 87,
      revenuePotential: 5,
    }),
    outcomes: ["activated trials", "pipeline"],
    dependencies: ["lead_generation"],
    difficulty: "medium",
    roiEstimate: 5,
    relatedEntitySlugs: ["trial_cta", "forms"],
  },
  {
    slug: "lifecycle_automation",
    name: "Lifecycle Automation Pattern",
    purpose: "Scale nurture and retention without manual work.",
    category: "automation",
    description: "Triggered email and CRM workflows across the journey.",
    profile: patternProfile({
      applicableIndustries: [],
      applicableBusinessModels: [],
      requiredConditions: ["automation", "drip", "crm", "workflow"],
      maturityLevels: ["growth", "scale"],
      goalTypes: ["leads", "revenue", "subscribers"],
      implementationSteps: impl([
        { title: "Map triggers", action: "List signup, purchase, and dormant events." },
        { title: "Build drips", action: "Ship welcome, onboarding, and win-back sequences." },
        { title: "Sync CRM", action: "Keep leads and stages synced automatically." },
      ]),
      impactScore: 79,
      revenuePotential: 4,
    }),
    outcomes: ["consistent nurture", "lower ops cost"],
    dependencies: ["newsletter"],
    difficulty: "medium",
    roiEstimate: 4,
    relatedEntitySlugs: ["email", "lifecycle_email", "crm_sync"],
  },
  {
    slug: "booking_automation",
    name: "Booking Automation Pattern",
    purpose: "Turn interest into scheduled revenue automatically.",
    category: "automation",
    description: "Self-serve booking and reminders for services businesses.",
    profile: patternProfile({
      applicableIndustries: ["local_services", "healthcare", "legal", "restaurants", "professional_services"],
      applicableBusinessModels: ["local_business", "lead_generation", "consulting"],
      requiredConditions: ["book", "appointment", "schedule", "reserv"],
      maturityLevels: ["early", "growth"],
      goalTypes: ["conversions", "leads"],
      implementationSteps: impl([
        { title: "Embed booking", action: "Add online booking on service pages." },
        { title: "Confirm + remind", action: "Automate confirmation and reminder messages." },
        { title: "Recover no-shows", action: "Send rebook prompts after misses." },
      ]),
      impactScore: 84,
      revenuePotential: 5,
    }),
    outcomes: ["more bookings", "fewer no-shows"],
    dependencies: [],
    difficulty: "easy",
    roiEstimate: 5,
    relatedEntitySlugs: ["booking_funnel"],
  },
  {
    slug: "ai_assistant_conversion",
    name: "AI Assistant Conversion Pattern",
    purpose: "Assist visitors in real time toward conversion.",
    category: "ai_adoption",
    description: "On-site AI chat that answers objections and routes to CTAs.",
    profile: patternProfile({
      applicableIndustries: ["saas", "ecommerce", "professional_services", "healthcare"],
      applicableBusinessModels: ["subscription", "product_commerce", "lead_generation"],
      requiredConditions: ["chat", "assistant", "ai", "help"],
      maturityLevels: ["growth", "scale"],
      goalTypes: ["conversions", "leads"],
      implementationSteps: impl([
        { title: "Scope FAQs", action: "Load product, pricing, and policy answers." },
        { title: "Route to CTA", action: "Hand off to demo, cart, or booking." },
        { title: "Review transcripts", action: "Improve answers from missed intents weekly." },
      ]),
      impactScore: 74,
      revenuePotential: 4,
    }),
    outcomes: ["higher assisted conversion", "support deflection"],
    dependencies: [],
    difficulty: "medium",
    roiEstimate: 4,
    relatedEntitySlugs: ["chat_assist"],
  },
  {
    slug: "ai_content_ops",
    name: "AI Content Ops Pattern",
    purpose: "Accelerate content production without losing quality control.",
    category: "ai_adoption",
    description: "AI-assisted drafting with human review for SEO and authority.",
    profile: patternProfile({
      applicableIndustries: ["creator_economy", "saas", "professional_services", "education"],
      applicableBusinessModels: ["digital_products", "subscription", "agency", "advertising"],
      requiredConditions: ["content", "blog", "ai", "draft"],
      maturityLevels: ["early", "growth", "scale"],
      goalTypes: ["seo", "authority", "subscribers"],
      implementationSteps: impl([
        { title: "Define briefs", action: "Create reusable topic briefs tied to pillars." },
        { title: "Draft with AI", action: "Generate first drafts, then expert-edit." },
        { title: "Publish cadence", action: "Ship on a fixed weekly schedule." },
      ]),
      impactScore: 72,
      revenuePotential: 3,
    }),
    outcomes: ["faster publishing", "SEO coverage"],
    dependencies: ["seo_pillar"],
    difficulty: "medium",
    roiEstimate: 3,
    relatedEntitySlugs: ["blog", "headless_cms"],
  },
  {
    slug: "donation_recurring",
    name: "Recurring Donation Pattern",
    purpose: "Convert one-time givers into monthly supporters.",
    category: "revenue",
    description: "Frictionless giving with recurring gift options for nonprofits.",
    profile: patternProfile({
      applicableIndustries: ["nonprofits", "churches"],
      applicableBusinessModels: ["nonprofit"],
      requiredConditions: ["donate", "give", "tithe", "offering"],
      maturityLevels: ["early", "growth", "scale"],
      goalTypes: ["revenue", "subscribers"],
      implementationSteps: impl([
        { title: "Simplify give CTA", action: "Put donate above the fold on every page." },
        { title: "Offer monthly", action: "Default to recurring with clear impact copy." },
        { title: "Thank + report", action: "Automate receipts and impact updates." },
      ]),
      impactScore: 88,
      revenuePotential: 5,
    }),
    outcomes: ["MRR giving", "donor retention"],
    dependencies: [],
    difficulty: "easy",
    roiEstimate: 5,
    relatedEntitySlugs: ["forms"],
  },
];

export const SEED_RULES: {
  slug: string;
  name: string;
  priority: number;
  conditions: KgRuleConditions;
  actions: KgRuleActions;
}[] = [
  {
    slug: "saas_missing_trial",
    name: "SaaS without free trial",
    priority: 90,
    conditions: { industry: "saas", missingSignals: ["trial", "free trial", "demo"] },
    actions: {
      boostCategories: ["conversion", "marketing", "revenue"],
      titleIncludes: ["trial", "demo", "pricing"],
      priorityBoost: 12,
      severityNudge: "high",
    },
  },
  {
    slug: "ecommerce_missing_reviews",
    name: "Ecommerce without reviews",
    priority: 80,
    conditions: { industry: "ecommerce", missingSignals: ["review", "rating", "testimonial"] },
    actions: {
      boostCategories: ["trust", "conversion"],
      titleIncludes: ["review", "testimonial", "social proof"],
      priorityBoost: 10,
    },
  },
  {
    slug: "local_missing_booking",
    name: "Local business without booking",
    priority: 85,
    conditions: {
      industry: "local_services",
      missingSignals: ["book", "appointment", "schedule", "reserv"],
    },
    actions: {
      boostCategories: ["conversion", "automation"],
      titleIncludes: ["book", "appoint", "schedul"],
      priorityBoost: 12,
    },
  },
  {
    slug: "church_missing_giving",
    name: "Church without online giving",
    priority: 80,
    conditions: { industry: "churches", missingSignals: ["give", "donate", "tithe", "offering"] },
    actions: {
      boostCategories: ["revenue", "conversion"],
      titleIncludes: ["giv", "donat"],
      priorityBoost: 14,
    },
  },
  {
    slug: "any_missing_newsletter",
    name: "Missing newsletter capture",
    priority: 60,
    conditions: { missingSignals: ["newsletter", "subscribe", "email list"] },
    actions: {
      boostCategories: ["marketing", "revenue"],
      titleIncludes: ["newsletter", "email", "subscribe"],
      priorityBoost: 8,
    },
  },
  {
    slug: "creator_missing_owned_list",
    name: "Creator without owned audience capture",
    priority: 85,
    conditions: {
      industry: "creator_economy",
      missingSignals: ["newsletter", "subscribe", "email", "membership"],
    },
    actions: {
      boostCategories: ["marketing", "revenue", "conversion"],
      titleIncludes: ["newsletter", "subscribe", "membership", "email"],
      priorityBoost: 12,
      severityNudge: "high",
    },
  },
  {
    slug: "bm_lead_gen_missing_cta",
    name: "Lead-gen model without clear CTA",
    priority: 88,
    conditions: {
      businessModel: "lead_generation",
      missingSignals: ["quote", "book", "contact", "consult", "demo"],
    },
    actions: {
      boostCategories: ["conversion", "marketing"],
      titleIncludes: ["cta", "quote", "book", "contact", "lead"],
      priorityBoost: 12,
      severityNudge: "high",
    },
  },
  {
    slug: "bm_commerce_missing_checkout",
    name: "Ecommerce model without strong checkout",
    priority: 88,
    conditions: {
      businessModel: "product_commerce",
      missingSignals: ["checkout", "cart", "buy"],
    },
    actions: {
      boostCategories: ["conversion", "revenue"],
      titleIncludes: ["checkout", "cart", "buy"],
      priorityBoost: 12,
    },
  },
  {
    slug: "pattern_missing_seo_content",
    name: "Missing SEO content foundation",
    priority: 65,
    conditions: { missingSignals: ["blog", "guide", "resources", "articles"] },
    actions: {
      boostCategories: ["content", "marketing"],
      titleIncludes: ["seo", "content", "blog", "organic"],
      priorityBoost: 8,
    },
  },
  {
    slug: "pattern_missing_ai_assist",
    name: "No on-site assistant for conversion",
    priority: 55,
    conditions: {
      industry: "saas",
      missingSignals: ["chat", "assistant", "live chat"],
    },
    actions: {
      boostCategories: ["conversion", "automation"],
      titleIncludes: ["chat", "assist", "support"],
      priorityBoost: 6,
    },
  },
];

function steps(
  items: { title: string; action: string; patternSlug?: string; moduleId?: string }[],
): KgPlaybookStep[] {
  return items.map((item, i) => ({ ...item, order: i + 1 }));
}

export const SEED_PLAYBOOKS: {
  slug: string;
  industrySlug: string;
  businessModelSlug?: string | null;
  name: string;
  steps: KgPlaybookStep[];
  patternSlugs: string[];
}[] = [
  {
    slug: "saas_growth",
    industrySlug: "saas",
    businessModelSlug: "subscription",
    name: "SaaS Growth Playbook",
    patternSlugs: ["trial_demo", "lead_generation", "newsletter", "authority", "retention", "upsell", "ai_assistant_conversion"],
    steps: steps([
      { title: "Clarify offer & pricing", action: "Publish clear pricing and packaging.", moduleId: "revenue", patternSlug: "upsell" },
      { title: "Add trial or demo path", action: "Ship a low-friction trial or demo CTA.", moduleId: "conversion", patternSlug: "trial_demo" },
      { title: "Capture product-led leads", action: "Add lead magnets and onboarding emails.", moduleId: "marketing", patternSlug: "newsletter" },
      { title: "Prove trust", action: "Add logos, case studies, and security signals.", moduleId: "trust", patternSlug: "authority" },
      { title: "Activate retention loops", action: "Automate onboarding and expansion nudges.", moduleId: "customer", patternSlug: "retention" },
      { title: "Assist conversions with AI", action: "Add on-site AI help for pricing and demos.", moduleId: "automation", patternSlug: "ai_assistant_conversion" },
    ]),
  },
  {
    slug: "ecommerce_growth",
    industrySlug: "ecommerce",
    businessModelSlug: "product_commerce",
    name: "Ecommerce Growth Playbook",
    patternSlugs: ["social_proof", "newsletter", "checkout_optimization", "upsell", "retention", "seo_pillar"],
    steps: steps([
      { title: "Improve product proof", action: "Surface reviews and guarantees on PDPs.", moduleId: "trust", patternSlug: "social_proof" },
      { title: "Capture emails", action: "Launch popup/lead magnet for list growth.", moduleId: "marketing", patternSlug: "newsletter" },
      { title: "Raise conversion", action: "Simplify checkout and CTAs.", moduleId: "conversion", patternSlug: "checkout_optimization" },
      { title: "Increase AOV", action: "Add bundles and post-purchase upsells.", moduleId: "revenue", patternSlug: "upsell" },
      { title: "Drive repeat purchase", action: "Automate win-back and replenishment flows.", moduleId: "customer", patternSlug: "retention" },
    ]),
  },
  {
    slug: "local_business_growth",
    industrySlug: "local_services",
    businessModelSlug: "local_business",
    name: "Local Business Growth Playbook",
    patternSlugs: ["local_seo", "booking_automation", "social_proof", "newsletter", "lead_generation"],
    steps: steps([
      { title: "Win local search", action: "Complete GBP and service-area pages.", moduleId: "marketing", patternSlug: "local_seo" },
      { title: "Make booking easy", action: "Add online booking above the fold.", moduleId: "conversion", patternSlug: "booking_automation" },
      { title: "Show proof", action: "Feature reviews and before/after work.", moduleId: "trust", patternSlug: "social_proof" },
      { title: "Own the list", action: "Capture emails for offers and reminders.", moduleId: "marketing", patternSlug: "newsletter" },
      { title: "Capture quotes", action: "Add a clear get-a-quote form.", moduleId: "conversion", patternSlug: "lead_generation" },
    ]),
  },
  {
    slug: "nonprofit_growth",
    industrySlug: "nonprofits",
    businessModelSlug: "nonprofit",
    name: "Nonprofit Growth Playbook",
    patternSlugs: ["donation_recurring", "newsletter", "authority", "community", "seo_pillar"],
    steps: steps([
      { title: "Simplify giving", action: "Put donate CTAs above the fold with recurring options.", moduleId: "revenue", patternSlug: "donation_recurring" },
      { title: "Tell impact stories", action: "Publish outcomes and beneficiary stories.", moduleId: "trust", patternSlug: "authority" },
      { title: "Grow the list", action: "Capture emails for campaigns and updates.", moduleId: "marketing", patternSlug: "newsletter" },
      { title: "Build community", action: "Engage donors and volunteers in one hub.", moduleId: "customer", patternSlug: "community" },
      { title: "Compound SEO", action: "Publish cause-related pillar content.", moduleId: "content", patternSlug: "seo_pillar" },
    ]),
  },
  {
    slug: "restaurant_growth",
    industrySlug: "restaurants",
    name: "Restaurant Growth Playbook",
    patternSlugs: ["booking_automation", "social_proof", "newsletter", "local_seo"],
    steps: steps([
      { title: "Make booking effortless", action: "Add reservation/order CTAs above the fold.", moduleId: "conversion", patternSlug: "booking_automation" },
      { title: "Strengthen local proof", action: "Feature reviews and photos prominently.", moduleId: "trust", patternSlug: "social_proof" },
      { title: "Own the guest list", action: "Collect emails for events and offers.", moduleId: "marketing", patternSlug: "newsletter" },
      { title: "Win local search", action: "Keep GBP and menus discoverable.", moduleId: "marketing", patternSlug: "local_seo" },
      { title: "Promote high-margin offers", action: "Highlight catering and events.", moduleId: "revenue" },
    ]),
  },
  {
    slug: "church_growth",
    industrySlug: "churches",
    businessModelSlug: "nonprofit",
    name: "Church Growth Playbook",
    patternSlugs: ["donation_recurring", "community", "newsletter", "seo_pillar"],
    steps: steps([
      { title: "Clarify the visit path", action: "Add clear service times and plan-a-visit CTA.", moduleId: "conversion" },
      { title: "Enable online giving", action: "Make giving frictionless and mobile-friendly.", moduleId: "revenue", patternSlug: "donation_recurring" },
      { title: "Publish sermons & stories", action: "Keep content fresh for seekers and members.", moduleId: "content", patternSlug: "community" },
      { title: "Build the list", action: "Offer a welcome email sequence.", moduleId: "marketing", patternSlug: "newsletter" },
    ]),
  },
  {
    slug: "agency_growth",
    industrySlug: "professional_services",
    businessModelSlug: "agency",
    name: "Agency Growth Playbook",
    patternSlugs: ["authority", "lead_generation", "newsletter", "referral", "lifecycle_automation", "ai_content_ops"],
    steps: steps([
      { title: "Package services", action: "Publish clear offers and outcomes.", moduleId: "revenue" },
      { title: "Publish proof", action: "Ship case studies and logos.", moduleId: "trust", patternSlug: "authority" },
      { title: "Capture demand", action: "Add consultation CTA and lead magnet.", moduleId: "marketing", patternSlug: "lead_generation" },
      { title: "Nurture pipeline", action: "Automate follow-ups and content drip.", moduleId: "automation", patternSlug: "lifecycle_automation" },
      { title: "Expand retainers", action: "Design upsell and referral loops.", moduleId: "customer", patternSlug: "referral" },
    ]),
  },
  {
    slug: "creator_economy_growth",
    industrySlug: "creator_economy",
    businessModelSlug: "membership",
    name: "Creator Growth Playbook",
    patternSlugs: ["newsletter", "membership", "authority", "seo_pillar", "ai_content_ops", "upsell"],
    steps: steps([
      { title: "Own the audience", action: "Put newsletter signup above the fold.", moduleId: "marketing", patternSlug: "newsletter" },
      { title: "Ship a clear offer", action: "Publish one membership or digital product page.", moduleId: "revenue", patternSlug: "membership" },
      { title: "Prove outcomes", action: "Add testimonials and sample content.", moduleId: "trust", patternSlug: "authority" },
      { title: "Automate nurture", action: "Welcome sequence + upsell drip after subscribe.", moduleId: "automation", patternSlug: "lifecycle_automation" },
      { title: "Compound content", action: "Pillar SEO content that feeds the list.", moduleId: "content", patternSlug: "seo_pillar" },
    ]),
  },
];

export const SEED_ENTITIES: { slug: string; name: string; type: string; description: string }[] = [
  { slug: "newsletter", name: "Newsletter", type: "marketing_channel", description: "Owned email audience" },
  { slug: "lead_magnet", name: "Lead magnet", type: "conversion_tactic", description: "Incentive for email capture" },
  { slug: "forms", name: "Forms", type: "conversion_tactic", description: "Site forms and CTAs" },
  { slug: "backlinks", name: "Backlinks", type: "authority_signal", description: "Inbound links and mentions" },
  { slug: "case_studies", name: "Case studies", type: "authority_signal", description: "Outcome stories" },
  { slug: "reviews", name: "Reviews", type: "trust_signal", description: "Third-party reviews" },
  { slug: "email", name: "Email automation", type: "automation_strategy", description: "Drip and lifecycle email" },
  { slug: "blog", name: "Blog / guides", type: "content_type", description: "Educational content" },
  { slug: "referral_program", name: "Referral program", type: "acquisition_method", description: "Customer referrals" },
  { slug: "onboarding", name: "Onboarding", type: "retention_strategy", description: "Activation and retention" },
  { slug: "membership", name: "Membership", type: "growth_opportunity", description: "Recurring membership access" },
  { slug: "community", name: "Community", type: "retention_strategy", description: "Peer community engagement" },
  { slug: "pricing", name: "Pricing page", type: "conversion_tactic", description: "Transparent packaging" },
  { slug: "packs", name: "Bundles / packs", type: "growth_opportunity", description: "Upsell packaging" },
  // Foundation entity types (Phase 13.1)
  { slug: "subscription_revenue", name: "Subscription revenue", type: "revenue_strategy", description: "Recurring subscription packaging and expansion" },
  { slug: "freemium_upsell", name: "Freemium upsell", type: "revenue_strategy", description: "Free tier to paid conversion path" },
  { slug: "product_sales", name: "Product sales", type: "revenue_strategy", description: "Direct product commerce and AOV lifts" },
  { slug: "trial_cta", name: "Free trial CTA", type: "conversion_strategy", description: "Prominent trial or demo conversion path" },
  { slug: "checkout_friction", name: "Checkout friction reduction", type: "conversion_strategy", description: "Fewer steps and trust cues at purchase" },
  { slug: "booking_funnel", name: "Booking funnel", type: "conversion_strategy", description: "Appointment and consultation conversion" },
  { slug: "local_seo", name: "Local SEO", type: "seo_strategy", description: "GBP, local pages, and map pack visibility" },
  { slug: "programmatic_seo", name: "Programmatic SEO", type: "seo_strategy", description: "Templated pages for scalable search coverage" },
  { slug: "comparison_seo", name: "Comparison / alternative pages", type: "seo_strategy", description: "High-intent comparison content for acquisition" },
  { slug: "crm_sync", name: "CRM sync", type: "automation_strategy", description: "Lead and customer data synced to CRM" },
  { slug: "lifecycle_email", name: "Lifecycle email", type: "automation_strategy", description: "Triggered nurture and retention sequences" },
  { slug: "headless_cms", name: "Headless CMS", type: "technology_pattern", description: "Composable content delivery for growth pages" },
  { slug: "analytics_stack", name: "Analytics stack", type: "technology_pattern", description: "Event tracking and conversion instrumentation" },
  { slug: "chat_assist", name: "Site chat / AI assist", type: "technology_pattern", description: "On-site assistance for conversion and support" },
];

export const SEED_RECOMMENDATIONS: {
  slug: string;
  name: string;
  summary: string;
  body: string;
  industrySlug?: string;
  businessModelSlug?: string;
  patternSlug?: string;
  moduleId?: string;
  priority: number;
}[] = [
  {
    slug: "saas_trial_cta",
    name: "Surface a free trial CTA",
    summary: "SaaS sites without a clear trial path under-convert high-intent visitors.",
    body: "Add a primary free trial or demo CTA above the fold and on pricing. Tie trial activation to onboarding emails.",
    industrySlug: "saas",
    patternSlug: "lead_generation",
    moduleId: "conversion",
    priority: 90,
  },
  {
    slug: "saas_case_studies",
    name: "Publish outcome case studies",
    summary: "B2B buyers need proof before trial or demo.",
    body: "Ship 2–3 case studies with metrics, logos, and a related CTA into trial or demo.",
    industrySlug: "saas",
    patternSlug: "authority",
    moduleId: "trust",
    priority: 80,
  },
  {
    slug: "ecommerce_trust_badges",
    name: "Strengthen checkout trust",
    summary: "Missing reviews and guarantees suppress ecommerce conversion.",
    body: "Add reviews, return policy, and secure-checkout cues on PDP and checkout.",
    industrySlug: "ecommerce",
    patternSlug: "retention",
    moduleId: "trust",
    priority: 85,
  },
  {
    slug: "ecommerce_email_capture",
    name: "Capture email before exit",
    summary: "Owned audience compounds repeat purchase.",
    body: "Offer a first-order incentive for email; nurture with abandoned cart and win-back flows.",
    industrySlug: "ecommerce",
    patternSlug: "newsletter",
    moduleId: "marketing",
    priority: 80,
  },
  {
    slug: "restaurant_local_seo",
    name: "Own local discovery",
    summary: "Restaurants win or lose on local search and reviews.",
    body: "Complete GBP, menu schema, reservation CTA, and review response cadence.",
    industrySlug: "restaurants",
    patternSlug: "lead_generation",
    moduleId: "seo",
    priority: 90,
  },
  {
    slug: "restaurant_reservations",
    name: "One-tap reservations",
    summary: "Friction to book is direct revenue leakage.",
    body: "Put reservation or ordering above the fold with hours and location.",
    industrySlug: "restaurants",
    moduleId: "conversion",
    priority: 85,
  },
  {
    slug: "church_giving",
    name: "Make giving obvious",
    summary: "Churches often bury donation paths.",
    body: "Add a clear give CTA, impact stories, and recurring giving option.",
    industrySlug: "churches",
    patternSlug: "membership",
    moduleId: "revenue",
    priority: 75,
  },
  {
    slug: "agency_proof",
    name: "Agency proof stack",
    summary: "Agencies convert with proof + consultation path.",
    body: "Feature logos, case studies, and a consultation CTA; automate nurture after form submit.",
    industrySlug: "professional_services",
    businessModelSlug: "agency",
    patternSlug: "authority",
    moduleId: "trust",
    priority: 80,
  },
  {
    slug: "local_services_booking",
    name: "Local booking + reviews",
    summary: "Local services need booking and social proof together.",
    body: "Pair online booking with review widgets and service-area pages for SEO.",
    industrySlug: "local_services",
    moduleId: "conversion",
    priority: 80,
  },
  {
    slug: "healthcare_booking_trust",
    name: "Healthcare booking with credentials",
    summary: "Patients book when trust and scheduling are both clear.",
    body: "Show credentials near a booking CTA; add condition FAQs for SEO and intake.",
    industrySlug: "healthcare",
    moduleId: "conversion",
    priority: 85,
  },
  {
    slug: "creator_owned_list",
    name: "Build an owned email list",
    summary: "Creators without an owned list rent attention from platforms.",
    body: "Put newsletter signup above the fold with a clear lead magnet; connect to a welcome sequence.",
    industrySlug: "creator_economy",
    patternSlug: "newsletter",
    moduleId: "marketing",
    priority: 90,
  },
  {
    slug: "bm_lead_gen_booking",
    name: "Make booking the primary CTA",
    summary: "Lead-gen models lose revenue when the next step is unclear.",
    body: "Put book-a-call or get-a-quote above the fold and route into CRM nurture.",
    businessModelSlug: "lead_generation",
    patternSlug: "lead_generation",
    moduleId: "conversion",
    priority: 88,
  },
  {
    slug: "bm_subscription_trial",
    name: "Clarify trial-to-paid path",
    summary: "Subscription models need an obvious trial or demo path.",
    body: "Surface trial/demo on pricing and homepage; automate activation emails.",
    businessModelSlug: "subscription",
    moduleId: "conversion",
    priority: 90,
  },
];
