import type { Metadata } from "next";
import { absoluteUrl, getSiteOrigin } from "./site";

export type BuildPageMetadataInput = {
  title: string;
  description: string;
  path: string;
  type?: "website" | "article";
  images?: string[];
  noIndex?: boolean;
};

/** Default share image — generated by src/app/opengraph-image.tsx (1200×630). */
export const SITE_OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "MoneyGap AI",
} as const;

export function buildPageMetadata(input: BuildPageMetadataInput): Metadata {
  const url = absoluteUrl(input.path);
  const customImages = (input.images ?? [])
    .filter(Boolean)
    .map((src) => (src.startsWith("http") ? src : absoluteUrl(src)));
  const ogImages =
    customImages.length > 0
      ? customImages.map((imageUrl) => ({ url: imageUrl }))
      : [
          {
            url: absoluteUrl(SITE_OG_IMAGE.url),
            width: SITE_OG_IMAGE.width,
            height: SITE_OG_IMAGE.height,
            alt: SITE_OG_IMAGE.alt,
          },
        ];
  const twitterImages =
    customImages.length > 0
      ? customImages
      : [absoluteUrl(SITE_OG_IMAGE.url)];

  return {
    title: input.title,
    description: input.description,
    metadataBase: new URL(getSiteOrigin()),
    alternates: { canonical: url },
    openGraph: {
      title: input.title,
      description: input.description,
      url,
      type: input.type ?? "website",
      siteName: "MoneyGap AI",
      images: ogImages,
    },
    twitter: {
      card: "summary_large_image",
      title: input.title,
      description: input.description,
      images: twitterImages,
    },
    robots: input.noIndex
      ? { index: false, follow: false }
      : { index: true, follow: true },
  };
}

export const SITE_DEFAULT_TITLE =
  "MoneyGap AI — Find the revenue you're leaving behind";
export const SITE_DEFAULT_DESCRIPTION =
  "MoneyGap AI helps growth teams find website revenue leaks with a developer-friendly conversion tool and codebase growth audit — then close gaps with Fix Paths™.";
