import Link from "next/link";
import { notFound } from "next/navigation";
import { eq } from "drizzle-orm";
import { Logo } from "@/components/logo";
import { Button } from "@/components/ui/button";
import { ThemeToggle } from "@/components/theme-toggle";
import { db } from "@/db";
import { extensionReports } from "@/db/schema";
import type {
  ExtensionFixPathItem,
  ExtensionMoneyGapReport,
} from "@/lib/extension-reports/types";
import { buildPageMetadata } from "@/lib/seo";

export const runtime = "nodejs";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ shareId: string }>;
}) {
  const { shareId } = await params;
  try {
    const [row] = await db
      .select({
        hostname: extensionReports.hostname,
        overallScore: extensionReports.overallScore,
      })
      .from(extensionReports)
      .where(eq(extensionReports.shareId, shareId))
      .limit(1);
    if (!row) {
      return buildPageMetadata({
        title: "Shared report",
        description: "MoneyGap AI Growth Intelligence Report from the browser extension.",
        path: `/report/ext/${shareId}`,
      });
    }
    return buildPageMetadata({
      title: `${row.hostname} — Score ${row.overallScore}`,
      description: `Shared MoneyGap Score™ ${row.overallScore} for ${row.hostname}.`,
      path: `/report/ext/${shareId}`,
    });
  } catch {
    return buildPageMetadata({
      title: "Shared report",
      description: "MoneyGap AI Growth Intelligence Report from the browser extension.",
      path: `/report/ext/${shareId}`,
    });
  }
}

function fixItems(report: ExtensionMoneyGapReport): ExtensionFixPathItem[] {
  if (report.fixPath && report.fixPath.length > 0) {
    return report.fixPath.slice(0, 12);
  }
  return (report.recommendations ?? []).slice(0, 12).map((rec) => ({
    id: rec.id,
    title: rec.title,
    whyItMatters: rec.whyItMatters ?? rec.reason,
    recommendation: rec.recommendation,
  }));
}

export default async function ExtensionPublicReportPage({
  params,
}: {
  params: Promise<{ shareId: string }>;
}) {
  const { shareId } = await params;

  if (!process.env.DATABASE_URL) {
    return (
      <div className="min-h-screen bg-bg px-5 py-16">
        <main className="mx-auto max-w-2xl">
          <h1 className="font-display text-xl font-semibold text-fg">
            Report unavailable
          </h1>
          <p className="mt-2 text-sm text-fg-muted">
            Cloud database is not configured.
          </p>
        </main>
      </div>
    );
  }

  let row: typeof extensionReports.$inferSelect | undefined;
  try {
    const rows = await db
      .select()
      .from(extensionReports)
      .where(eq(extensionReports.shareId, shareId))
      .limit(1);
    row = rows[0];
  } catch {
    notFound();
  }

  if (!row) notFound();

  const report = row.payload as ExtensionMoneyGapReport;
  const items = fixItems(report);
  const analyzedAt = row.createdAt.toLocaleString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });

  return (
    <div className="min-h-screen bg-bg">
      <header className="border-b border-border/70 bg-bg/80 backdrop-blur-xl">
        <div className="mx-auto flex h-16 max-w-3xl items-center justify-between px-5 sm:px-8">
          <Logo href="/" />
          <div className="flex items-center gap-2">
            <ThemeToggle />
            <Button href="/sign-up" size="sm">
              Get MoneyGap AI
            </Button>
          </div>
        </div>
      </header>

      <main>
        <section className="relative overflow-hidden bg-hero">
          <div className="pointer-events-none absolute inset-0 bg-grid opacity-70" />
          <div className="relative mx-auto max-w-3xl px-5 py-14 sm:px-8 sm:py-20">
            <p className="text-xs font-semibold uppercase tracking-[0.14em] text-accent">
              Shared Growth Intelligence Report
            </p>
            <h1 className="mt-3 font-display text-4xl font-semibold tracking-tight text-fg sm:text-5xl">
              {row.hostname}
            </h1>
            <p className="mt-3 text-lg text-fg-muted">
              MoneyGap Score™{" "}
              <span className="font-semibold tabular-nums text-fg">
                {row.overallScore}
              </span>
              <span className="text-fg-subtle"> · {analyzedAt}</span>
            </p>
            <p className="mt-2 text-sm text-fg-subtle">
              Generated by the MoneyGap AI browser extension · MoneyGap Engine™
            </p>
          </div>
        </section>

        <section className="mx-auto max-w-3xl space-y-4 px-5 py-12 sm:px-8">
          <h2 className="font-display text-lg font-semibold text-fg">
            Fix Path™
          </h2>
          {items.length === 0 ? (
            <p className="text-sm text-fg-muted">
              No prioritized fixes were included in this share.
            </p>
          ) : (
            <ol className="space-y-3">
              {items.map((item, i) => (
                <li
                  key={item.id || String(i)}
                  className="rounded-xl border border-border/80 bg-bg-elevated/40 p-4"
                >
                  <p className="text-sm font-semibold text-fg">
                    {i + 1}. {item.title}
                  </p>
                  {item.whyItMatters ? (
                    <p className="mt-1 text-xs leading-relaxed text-fg-muted">
                      {item.whyItMatters}
                    </p>
                  ) : null}
                  {item.recommendation ? (
                    <p className="mt-2 text-xs font-medium text-accent">
                      Fix Path™: {item.recommendation}
                    </p>
                  ) : null}
                </li>
              ))}
            </ol>
          )}

          <div className="pt-6">
            <Button href="/features" variant="secondary" size="sm">
              Explore MoneyGap AI
            </Button>
            <p className="mt-3 text-xs text-fg-subtle">
              Want deeper analysis, monitoring, and Growth Badge™ verification?{" "}
              <Link href="/sign-up" className="text-accent underline-offset-2 hover:underline">
                Create a free account
              </Link>
              .
            </p>
          </div>
        </section>
      </main>
    </div>
  );
}
