import { cn } from "@/lib/utils";

export const AI_ESTIMATE_DISCLAIMER =
  "This estimate is generated by AI using the website's visible content, business model, industry, and comparable business patterns. It is intended as strategic guidance and not as a guarantee of financial results.";

export function EstimateDisclaimer({ className }: { className?: string }) {
  return (
    <p
      className={cn(
        "rounded-xl border border-border bg-bg-muted/50 px-4 py-3 text-xs leading-relaxed text-fg-subtle",
        className,
      )}
    >
      {AI_ESTIMATE_DISCLAIMER}
    </p>
  );
}
