import type { TopicId, TopicMeta } from "./types";

export const TOPICS: TopicMeta[] = [
  {
    id: "core-web-vitals",
    slug: "core-web-vitals",
    name: "Core Web Vitals",
    category: "performance",
    difficulty: "intermediate",
    tags: ["lcp", "inp", "cls", "cwv"],
    summary: "Measure and improve LCP, INP, and CLS for real-user experience.",
  },
  {
    id: "seo",
    slug: "seo",
    name: "SEO",
    category: "seo",
    difficulty: "beginner",
    tags: ["search", "crawl", "rankings"],
    summary: "Technical SEO foundations for crawlable, indexable pages.",
  },
  {
    id: "ai-readiness",
    slug: "ai-readiness",
    name: "AI Readiness",
    category: "ai",
    difficulty: "intermediate",
    tags: ["ai", "assistants", "aeo"],
    summary: "Prepare sites for AI assistants and answer engines.",
  },
  {
    id: "llms-txt",
    slug: "llms-txt",
    name: "llms.txt",
    category: "ai",
    difficulty: "beginner",
    tags: ["llms", "ai-crawlers", "guidance"],
    summary: "Publish an AI guidance file describing your org and canonical URLs.",
  },
  {
    id: "metadata",
    slug: "metadata",
    name: "Metadata",
    category: "metadata",
    difficulty: "beginner",
    tags: ["title", "description", "head"],
    summary: "Titles, descriptions, and document metadata that drive SERP quality.",
  },
  {
    id: "open-graph",
    slug: "open-graph",
    name: "Open Graph",
    category: "metadata",
    difficulty: "beginner",
    tags: ["og", "social"],
    summary: "Social preview metadata for link unfurls.",
  },
  {
    id: "twitter-cards",
    slug: "twitter-cards",
    name: "Twitter Cards",
    category: "metadata",
    difficulty: "beginner",
    tags: ["twitter", "x", "social"],
    summary: "Card metadata for X/Twitter link previews.",
  },
  {
    id: "schema-org",
    slug: "schema-org",
    name: "Schema.org",
    category: "structured-data",
    difficulty: "intermediate",
    tags: ["json-ld", "structured-data"],
    summary: "Machine-readable entity markup for search and AI systems.",
  },
  {
    id: "faq-schema",
    slug: "faq-schema",
    name: "FAQ Schema",
    category: "structured-data",
    difficulty: "beginner",
    tags: ["faq", "json-ld"],
    summary: "FAQPage structured data for Q&A content.",
  },
  {
    id: "organization-schema",
    slug: "organization-schema",
    name: "Organization Schema",
    category: "structured-data",
    difficulty: "beginner",
    tags: ["organization", "entity"],
    summary: "Organization JSON-LD for brand entity clarity.",
  },
  {
    id: "canonical-urls",
    slug: "canonical-urls",
    name: "Canonical URLs",
    category: "seo",
    difficulty: "intermediate",
    tags: ["canonical", "duplicates"],
    summary: "Declare preferred URLs to prevent duplicate-content dilution.",
  },
  {
    id: "robots-txt",
    slug: "robots-txt",
    name: "Robots.txt",
    category: "crawl",
    difficulty: "beginner",
    tags: ["robots", "crawl"],
    summary: "Control crawler access with robots.txt.",
  },
  {
    id: "sitemap-xml",
    slug: "sitemap-xml",
    name: "Sitemap.xml",
    category: "crawl",
    difficulty: "beginner",
    tags: ["sitemap", "index"],
    summary: "Expose indexable URLs via XML sitemaps.",
  },
  {
    id: "accessibility",
    slug: "accessibility",
    name: "Accessibility",
    category: "a11y",
    difficulty: "intermediate",
    tags: ["a11y", "wcag", "aria"],
    summary: "Semantic HTML, labels, and accessible media.",
  },
  {
    id: "image-optimization",
    slug: "image-optimization",
    name: "Image Optimization",
    category: "media",
    difficulty: "intermediate",
    tags: ["images", "lcp", "webp"],
    summary: "Responsive images, formats, and dimensions for performance.",
  },
  {
    id: "hydration",
    slug: "hydration",
    name: "Hydration Failures",
    category: "performance",
    difficulty: "intermediate",
    tags: ["hydration", "ssr", "react", "mismatch"],
    summary:
      "Fix React/Next hydration mismatches that break interactivity, SEO trust, and Core Web Vitals.",
  },
  {
    id: "performance",
    slug: "performance",
    name: "Performance",
    category: "performance",
    difficulty: "intermediate",
    tags: ["speed", "bundle"],
    summary: "Broader performance beyond Core Web Vitals alone.",
  },
  {
    id: "caching",
    slug: "caching",
    name: "Caching",
    category: "infra",
    difficulty: "intermediate",
    tags: ["cdn", "cache-control"],
    summary: "HTTP caching and CDN strategies for static and dynamic assets.",
  },
  {
    id: "fonts",
    slug: "fonts",
    name: "Fonts",
    category: "performance",
    difficulty: "beginner",
    tags: ["fonts", "cls", "foit"],
    summary: "Load fonts without blocking render or shifting layout.",
  },
  {
    id: "routing",
    slug: "routing",
    name: "Routing",
    category: "infra",
    difficulty: "beginner",
    tags: ["routes", "urls"],
    summary: "Clean URL structures and crawlable navigation.",
  },
  {
    id: "security-headers",
    slug: "security-headers",
    name: "Security Headers",
    category: "security",
    difficulty: "intermediate",
    tags: ["csp", "hsts", "headers"],
    summary: "HTTP security headers that protect users and trust signals.",
  },
  {
    id: "structured-data",
    slug: "structured-data",
    name: "Structured Data",
    category: "structured-data",
    difficulty: "intermediate",
    tags: ["json-ld", "rich-results"],
    summary: "Overview of structured data patterns beyond a single schema type.",
  },
  {
    id: "deployment",
    slug: "deployment",
    name: "Deployment",
    category: "infra",
    difficulty: "intermediate",
    tags: ["deploy", "hosting"],
    summary: "Ship crawlable builds with correct env, redirects, and headers.",
  },
  {
    id: "analytics",
    slug: "analytics",
    name: "Analytics",
    category: "growth",
    difficulty: "beginner",
    tags: ["analytics", "consent"],
    summary: "Instrument growth metrics without breaking privacy or performance.",
  },
  {
    id: "conversion-optimization",
    slug: "conversion-optimization",
    name: "Conversion Optimization",
    category: "growth",
    difficulty: "intermediate",
    tags: ["cta", "forms", "cro"],
    summary: "CTAs, forms, and journey friction that block capture.",
  },
  {
    id: "trust-signals",
    slug: "trust-signals",
    name: "Trust Signals",
    category: "growth",
    difficulty: "beginner",
    tags: ["trust", "privacy", "security"],
    summary: "Privacy, terms, contact, and proof that build buyer confidence.",
  },
];

export function getTopic(idOrSlug: string): TopicMeta | undefined {
  return TOPICS.find((t) => t.id === idOrSlug || t.slug === idOrSlug);
}

export function isTopicId(v: string): v is TopicId {
  return TOPICS.some((t) => t.id === v);
}

export const CATEGORY_LABELS: Record<TopicMeta["category"], string> = {
  performance: "Performance",
  seo: "SEO",
  ai: "AI Readiness",
  metadata: "Metadata",
  "structured-data": "Structured Data",
  crawl: "Crawl & Index",
  a11y: "Accessibility",
  media: "Media",
  infra: "Infrastructure",
  growth: "Growth",
  security: "Security",
};
