import { and, eq } from "drizzle-orm";
import { db } from "@/db";
import {
  developerImplementationPlans,
  developerPrDrafts,
  developerRepos,
} from "@/db/schema";
import { writeDeveloperAudit } from "@/lib/developer/audit";
import {
  createBranch,
  createOrUpdateFile,
  createPullRequest,
  DeveloperGithubError,
  getBranchSha,
  getGithubAccessToken,
} from "@/lib/developer/github-api";
import { summarizeRisk } from "@/lib/developer/risk";

const PROTECTED = new Set(["main", "master", "production", "prod"]);

function branchSlug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 36) || "plan";
}

export async function createDraftPrFromPlan(input: {
  workspaceId: string;
  userId: string;
  planId: string;
}) {
  const plan = await db.query.developerImplementationPlans.findFirst({
    where: and(
      eq(developerImplementationPlans.id, input.planId),
      eq(developerImplementationPlans.workspaceId, input.workspaceId),
    ),
  });
  if (!plan) {
    return { ok: false as const, error: "Plan not found", status: 404 as const };
  }

  const repoId = plan.repoId;
  if (!repoId) {
    return {
      ok: false as const,
      error: "Plan has no linked repository. Sync and analyze a repo first.",
      status: 400 as const,
    };
  }

  const repo = await db.query.developerRepos.findFirst({
    where: and(
      eq(developerRepos.id, repoId),
      eq(developerRepos.workspaceId, input.workspaceId),
    ),
  });
  if (!repo) {
    return { ok: false as const, error: "Repository not found", status: 404 as const };
  }

  const base = repo.defaultBranch || "main";
  // Base may be main/master; head must never be a protected production branch.

  const token = await getGithubAccessToken(input.workspaceId);
  if (!token) {
    return {
      ok: false as const,
      error:
        "GitHub is not connected. Connect it in Integration Hub before creating a PR.",
      status: 503 as const,
    };
  }

  const branchName = `moneygap/${branchSlug(plan.title)}-${Date.now().toString(36).slice(-4)}`;
  if (PROTECTED.has(branchName.toLowerCase()) || !branchName.startsWith("moneygap/")) {
    return {
      ok: false as const,
      error: "Refusing non-feature branch target",
      status: 400 as const,
    };
  }

  const riskSummary = summarizeRisk(plan.plan);
  const now = new Date();

  try {
    const sha = await getBranchSha(token, repo.fullName, base);
    await createBranch(token, repo.fullName, branchName, sha);

    const planMd = [
      `# ${plan.title}`,
      "",
      plan.plan.summary,
      "",
      `Risk: ${plan.plan.riskLevel} — ${plan.plan.riskSummary}`,
      "",
      "## Files to create",
      ...plan.plan.filesCreate.map((f) => `- ${f}`),
      "",
      "## Files to update",
      ...plan.plan.filesUpdate.map((f) => `- ${f}`),
      "",
      "## Validation",
      ...plan.plan.validationChecklist.map((f) => `- [ ] ${f}`),
      "",
      "## Testing",
      ...plan.plan.testingSteps.map((f) => `- ${f}`),
      "",
      "## Rollback",
      ...plan.plan.rollbackSteps.map((f) => `- ${f}`),
      "",
      "_Generated by MoneyGap Developer Mode™. Do not merge without human review._",
    ].join("\n");

    await createOrUpdateFile(
      token,
      repo.fullName,
      `.moneygap/plans/${plan.id}.md`,
      planMd,
      `chore(moneygap): add implementation plan for ${plan.title}`,
      branchName,
    );

    const prBody = [
      plan.plan.summary,
      "",
      `**Risk:** ${plan.plan.riskLevel} — ${plan.plan.riskSummary}`,
      "",
      "### Rollback",
      ...plan.plan.rollbackSteps.map((s) => `- ${s}`),
      "",
      "Draft PR created by MoneyGap Developer Mode™. Never merges to production automatically.",
      "",
      `Plan artifact: \`.moneygap/plans/${plan.id}.md\``,
    ].join("\n");

    const pr = await createPullRequest(token, repo.fullName, {
      title: `[MoneyGap] ${plan.title}`,
      body: prBody,
      head: branchName,
      base,
      draft: true,
    });

    const [draft] = await db
      .insert(developerPrDrafts)
      .values({
        workspaceId: input.workspaceId,
        planId: plan.id,
        repoId: repo.id,
        branchName,
        prUrl: pr.html_url,
        prNumber: pr.number,
        status: "open",
        riskSummary,
        authorizedByUserId: input.userId,
        authorizedAt: now,
        meta: { base },
      })
      .returning();

    await writeDeveloperAudit({
      workspaceId: input.workspaceId,
      actorUserId: input.userId,
      action: "developer_pr_create",
      repoId: repo.id,
      planId: plan.id,
      meta: { branchName, prNumber: pr.number, prUrl: pr.html_url },
    });

    return { ok: true as const, draft: draft! };
  } catch (e) {
    const msg =
      e instanceof DeveloperGithubError ? e.message : "Could not create draft PR";
    const [failed] = await db
      .insert(developerPrDrafts)
      .values({
        workspaceId: input.workspaceId,
        planId: plan.id,
        repoId: repo.id,
        branchName,
        status: "failed",
        riskSummary,
        authorizedByUserId: input.userId,
        authorizedAt: now,
        meta: { error: msg },
      })
      .returning();

    await writeDeveloperAudit({
      workspaceId: input.workspaceId,
      actorUserId: input.userId,
      action: "developer_pr_failed",
      repoId: repo.id,
      planId: plan.id,
      meta: { error: msg, branchName },
    });

    return {
      ok: false as const,
      error: msg,
      status: 502 as const,
      draft: failed,
    };
  }
}
