import type { PlaybookId } from "@/lib/advisor/playbooks";

const CHECKLISTS: Record<PlaybookId, string[]> = {
  newsletter: [
    "Choose email platform",
    "Create signup form",
    "Write lead magnet",
    "Design popup / embed",
    "Create welcome email",
    "Write first five newsletter drafts",
    "Connect automation",
    "Launch",
    "Measure opens, clicks, and conversions",
  ],
  faq: [
    "Collect top customer questions",
    "Draft 30 FAQs with answers",
    "Add FAQ schema markup",
    "Publish FAQ page",
    "Link FAQ from homepage and support",
    "Measure support deflection / SEO traffic",
  ],
  testimonials: [
    "Identify happy customers to ask",
    "Send testimonial request email",
    "Collect reviews / quotes",
    "Build testimonials section on site",
    "Add logos / outcomes where available",
    "Publish and promote social proof",
  ],
  backlinks: [
    "Define target sites and anchors",
    "Draft guest post ideas",
    "Build outreach email templates",
    "Send first outreach batch",
    "Follow up",
    "Track placements and referral traffic",
  ],
  lead_magnet: [
    "Pick magnet format",
    "Outline content",
    "Write / design magnet",
    "Create landing page",
    "Connect email capture",
    "Launch and promote",
    "Measure opt-in rate",
  ],
  digital_product: [
    "Validate top product idea",
    "Define positioning and pricing",
    "Draft sales page",
    "Build delivery / access",
    "Create launch plan",
    "Market and sell",
    "Collect feedback and iterate",
  ],
  seo_content: [
    "Identify top buyer-intent keywords for the offer",
    "Prioritize 3–5 long-tail topics for first drafts",
    "Draft first targeted blog posts for human review",
    "Build a 90-day buyer-intent content calendar",
    "Add internal links from new drafts to pricing / home",
    "Outline FAQ or comparison pages for decision-stage queries",
    "Publish reviewed drafts outside MoneyGap (human approval)",
    "Measure organic traffic, leads, and conversions (AI Estimate baseline)",
  ],
  site_chatbot: [
    "List top FAQs and objections for the offer",
    "Draft automated FAQ replies for human review",
    "Design lead-qualify questions and routing rules",
    "Choose a chatbot tool (Intercom, Drift, or similar) — config draft only",
    "Write sample conversation scripts with CTAs to trial / demo / sales",
    "Review transcripts and handoff rules before go-live",
    "Enable reviewed bot outside MoneyGap (human approval)",
    "Measure chat starts, qualified leads, and conversions (AI Estimate baseline)",
  ],
  schema_markup: [
    "Audit key offer / product / service pages for missing structured data",
    "Choose @types (Organization, Product, Service, Offer, FAQPage)",
    "Draft JSON-LD for main offers for human review",
    "Note placement: script type application/ld+json on each page",
    "Validate with Rich Results Test before go-live",
    "Paste reviewed markup outside MoneyGap (human approval)",
    "Re-scan the site after deploy",
    "Measure rich-result eligibility / CTR movement (AI Estimate baseline)",
  ],
  generic: [
    "Clarify the desired business outcome",
    "Define the smallest shippable version",
    "Assign owner and deadline",
    "Implement Quick Win",
    "Implement Medium Effort step",
    "Ship and measure impact",
  ],
};

export function checklistForPlaybook(playbook: PlaybookId): string[] {
  return [...(CHECKLISTS[playbook] ?? CHECKLISTS.generic)];
}
